[package]
name = "cryptools"
version = "0.11.0"
authors = ["scoobybejesus <scoobybejesus@users.noreply.github.com>"]
edition = "2018"
description = "Command-line utility for processing cryptocurrency transactions into 'lots' and 'movements'."

[[bin]]
name = "cryptools"
path = "src/main.rs"

[workspace]

[dependencies]
crptls = { path = "crptls" }
csv = "1.0.0"
decimal = "2.0.4"
chrono = { version = "0.4", features = ["serde"] }
structopt = "0.2.10"
rustyline = "5.0.0"
tui = "0.5"
termion = "1.5"
dotenv = "0.14.1"

[profile.release]
lto = true